-   id: check-rspec
    name: check rspec against recipes
    entry: check-rspec
    language: python
    files: '\.rb$'
    always_run: true
-   id: check-cookstyle
    name: check cookstyle against cookbooks
    entry: check-cookstyle
    language: python
    files: '\.rb$'
    always_run: true
-   id: check-foodcritic
    name: check foodcritic against cookbooks
    entry: check-foodcritic
    language: python
    files: ''
    always_run: true
