language: python
python: 3.5
env: # These should match the tox env list
    - TOXENV=py27
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=pypy
install: pip install coveralls tox
script: tox
before_install:
  # Install git-lfs for a test
  - './get-git-lfs.py && export PATH="/tmp/git-lfs:$PATH"'
after_success:
    - coveralls
sudo: false
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.pre-commit
        - /tmp/git-lfs
